version: "3.9"

services:
  sukmagame-html-webapp:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - office-network
  sukmagame-html-proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 8075:${NGINX_PORT}
    depends_on:
      - sukmagame-html-webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - office-network

networks:
  office-network:
    external: true
    name: office-network
